[template]
  incoming-hooks = ["Contentful"]

[template.environment]
  CONTENTFUL_SPACE_ID = "w91en02h7ign"
  CONTENTFUL_ACCESS_TOKEN = "GpyadInqRzDThWxyjBcRODEY7-JuBWyVs5IcgEjm8h0"
  CONTENTFUL_PREVIEW_ACCESS_TOKEN = "IXvPz6G8waeJZVb9Pqg-_1uEVgMYwMGdqOTFHi8ntuM"
